name: netpyne
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.7.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - bokeh==2.4.3
    - contextlib2==21.6.0
    - cycler==0.11.0
    - fonttools==4.38.0
    - future==0.18.3
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - lfpykit==0.5
    - markupsafe==2.1.2
    - matplotlib==3.5.1
    - matplotlib-scalebar==0.8.1
    - meautility==1.5.1
    - mpi4py==3.1.4
    - netpyne==1.0.3.1
    - neuron==8.2.2
    - numpy==1.21.6
    - packaging==23.0
    - pandas==1.3.5
    - pillow==9.4.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pyyaml==6.0
    - schema==0.7.5
    - scipy==1.7.3
    - six==1.16.0
    - tornado==6.2
    - typing-extensions==4.4.0
